version: '2'
exclude_patterns:
  - '.next/'
  - '/flow-typed/'
  - 'apiserver/'
  - 'data/constants.js'
  - 'data/mocks.js'
  - 'node_modules/'
  - 'pages/_document.js'

checks:
  method-lines:
    config:
      threshold: 50
