language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  app: car-gallery-demo
  api_key:
    secure: JIlQC4nbhVNREKoCZXaiMoWwas0vZAb2NbT6ADlzfUHesrnGOLIIb0DZAs1CsgxdTQlzpl89vHUN9BUJx1PO8TE0TIYoJiKQ/nIYAHluBUn0Fo6Qe0RtrQYCDkXZ5YfuHE0ufbekAa7aJnhYnMqUNKRDiew74BBeyUSyQgi2CfXQrVTeBQEf9DnnoRdF5w84/q0AnYijTfy/z16mNpBy47c+2Iotuc6v4nb9hlJ7WmS+9DmkXZJnPsU0m7onOAKJgnhv/vAadKa8J8dlPuU6AhwpEHFbHJ0JBLo8aYcGFdHjyZR87XfwfM36CiHE6u3yrr9dWy2AFIC0ItnLdB3Kl15/pi5CtCsw2A2tyYlW5d6AkyUChb72+jrPgVP7voTNnjxJWC8c+4gMm5z4YwCvJkHCC8xYqyE4nOALGOY2G7OSJlod4YG38NYvTFIlIRyOo8XnX1LPeeIQJBMDm8btBMD65vlInpiUotJh08+qy0qfUA8/Pvv8SxGZM/U5hviOtxyQSYrSbpNrWmM9e3aGMwTmRSszY0/SKvfHvsA0h2RWTTO/sZOm3OURLRDE76FSIKYgmckA1/Qp0DcNymjFaJvYiFX+rJiRp6tCJOGUi1pZGzruxrPqSO3lIkwkWNPa8hK41XWspO00veoQecdB0TxxX6Zxo8ZOiBt6E3nvAZI=
